---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        service: worker
    spec:
      containers:
        - name: worker
          image: kindlyops/havenworker
          env:
            - name: DATABASE_NAME
              value: "havenstage"
            - name: DATABASE_HOST
              value: "db"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: haven-database-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: haven-database-credentials
                  key: password
            - name: FAKTORY_URL
              valueFrom:
                secretKeyRef:
                  name: haven-faktory-credentials
                  key: url
            - name: KC_ADMIN
              value: "admin"
            - name: KC_PW
              valueFrom:
                secretKeyRef:
                  name: haven-database-credentials
                  key: password
            - name: KC_HOST
              value: https://staging.havengrc.com
            - name: SENTRY_ENVIRONMENT
              value: "staging"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn
          volumeMounts:
            - mountPath: "/home/rstudio/kitematic"
              name: worker-vol
      volumes:
        - name: worker-vol
          persistentVolumeClaim:
          claimName: worker-volume
      restartPolicy: Always
  strategy:
    type: "Recreate"
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0
status: {}
